### ISSUE TITLE
BedClock cycles without gesture

### ISSUE THREAD

**Issue by bobjimman** [flavio-fernandes/bedclock#1]
Hi
I was looking for some help
I've install this bedclock software on a pi zero
I followed Adafruits learn and yours, The clock cycles on every 10 seconds without gesturing.
Tested the sensors following Adafruit guide for the 9960 and ran example code on a arduino.
The 9960 works fine there I see the motion in the serial console.
At a lost what to try next

**Comment by flavio-fernandes** [comment]
> Hi
> I was looking for some help
> I've install this bedclock software on a pi zero
> I followed Adafruits learn and yours, The clock cycles on every 10 seconds without gesturing.
> Tested the sensors following Adafruit guide for the 9960 and ran example code on a arduino.
> The 9960 works fine there I see the motion in the serial console.
> At a lost what to try next

Hello @bobjimman ! Sorry to hear about your issue. 
If you look at a file called const.py, try adjusting these values to better condition for your light environment:  

https://github.com/flavio-fernandes/bedclock/blob/c8082621de002e708060304a53a33e455b43ac4b/bedclock/const.py#L51-L52

Assuming you are on a shell in the RPI device. Check a few things.
First, take a look at the current lux values that your sensor is giving you, so you have a good idea of what
min and max you should be using:

```
grep "lux raw" /home/pi/bedclock.git/syslog.log | tail -5
```

Try the command above when the light in the room is on and off, so you get a good feel for the range
you should be using.

Then,  using an editor like:

```
nano /home/pi/bedclock.git/bedclock/const.py
```

change the values, save the file and quit nano. Then restart the program using:

```
sudo systemctl restart bedclock.service
```

Try it out, repeat as often as needed.
Hope this helps. 


-- flaviof

**Comment by bobjimman** [comment]
Hello flaviof

Thanks for the quick reply but I changed the the 2 quantities you suggested with no change.
I adjusted the values from 0 to 300.
Seems like the Pi does not see the sensor, is there a library I should check.

Thanks
bobjimman

**Comment by bobjimman** [comment]
Hi
I started over again new sd card new Adafruit 6660 this one has STEMMA QT but I soldered the connection
After all this I get same results but I did see a repeating error maybe this means something to you.

Jul 28 18:33:44 PiGesture bedclock[2377]: Process MotionProcess-1:
Jul 28 18:33:44 PiGesture bedclock[2377]: Traceback (most recent call last):
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 154, in __probe_for_device
Jul 28 18:33:44 PiGesture bedclock[2377]:     self.i2c.writeto(self.device_address, b"")
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/busio.py", line 159, in writeto
Jul 28 18:33:44 PiGesture bedclock[2377]:     return self._i2c.writeto(address, buffer, stop=stop)
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 49, in writeto
Jul 28 18:33:44 PiGesture bedclock[2377]:     self._i2c_bus.write_bytes(address, buffer[start:end])
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 314, in write_bytes
Jul 28 18:33:44 PiGesture bedclock[2377]:     self._device.write(buf)
Jul 28 18:33:44 PiGesture bedclock[2377]: OSError: [Errno 121] Remote I/O error
Jul 28 18:33:44 PiGesture bedclock[2377]: During handling of the above exception, another exception occurred:
Jul 28 18:33:44 PiGesture bedclock[2377]: Traceback (most recent call last):
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 160, in __probe_for_device
Jul 28 18:33:44 PiGesture bedclock[2377]:     self.i2c.readfrom_into(self.device_address, result)
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/busio.py", line 149, in readfrom_into
Jul 28 18:33:44 PiGesture bedclock[2377]:     return self._i2c.readfrom_into(address, buffer, stop=stop)
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 56, in readfrom_into
Jul 28 18:33:44 PiGesture bedclock[2377]:     readin = self._i2c_bus.read_bytes(address, end - start)
Jul 28 18:33:44 PiGesture bedclock[2377]:   File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 181, in read_bytes
Jul 28 18:33:44 PiGesture bedclock[2377]:     return self._device.read(number)
Jul 28 18:33:44 PiGesture bedclock[2377]: OSError: [Errno 121] Remote I/O error

Thanks bobjimman

**Comment by flavio-fernandes** [comment]
Hmm.... sounds like you are having issues with the device indeed.

Take a look at https://github.com/adafruit/Adafruit_CircuitPython_APDS9960 and see if you can get the basic examples working. Just to be clear, you are using the APDS9960 , not the 6660 right? I'm assuming you had a typo there.

Another place to try is the [discord for Adafruit](http://adafru.it/discord) folks. They know a lot about the [i2c device](https://circuitpython.readthedocs.io/projects/busdevice/en/latest/_modules/adafruit_bus_device/i2c_device.html).

**Comment by bobjimman** [comment]
Hi Flavio
I started the Bedclock new with a new pi SD card and a new APDS9960.The response is identical as before every  10 seconds the display lights up regardless of gesture.In syslog.log it shows why 
            Aug 12 12:03:52 raspberrypi bedclock[1507]: Traceback (most recent call last):Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "/usr/lib/python3.7/multiprocAug 12 12:03:52 raspberrypi bedclock[1507]:     self.run()Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "./main.py", line 57, in runAug 12 12:03:52 raspberrypi bedclock[1507]:     motion.do_iterate()Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "/home/pi/bedclock.git/bedcloAug 12 12:03:52 raspberrypi bedclock[1507]:     do_iterate_proximity()Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "/home/pi/bedclock.git/bedcloAug 12 12:03:52 raspberrypi bedclock[1507]:     newProximity = _state.apds.proxiAug 12 12:03:52 raspberrypi bedclock[1507]: TypeError: 'int' object is not callalines 1-21/21 (END)...skipping...
does this log give you a hint at what could be wrongI have not found help anywhere else and am about to abandoned this project
Thanks again for your help

Jim






    On Wednesday, July 28, 2021, 08:53:45 PM EDT, Flavio Fernandes ***@***.***> wrote:  
 
 


Hmm.... sounds like you are having issues with the device indeed.

Take a look at https://github.com/adafruit/Adafruit_CircuitPython_APDS9960 and see if you can get the basic examples working. Just to be clear, you are using the APDS9960 , not the 6660 right? I'm assuming you had a typo there.

Another place to try is the discord for Adafruit folks. They know a lot about the i2c device.

**Comment by flavio-fernandes** [comment]
> Hi Flavio I started the Bedclock new with a new pi SD card and a new APDS9960.The response is identical as before every  10 seconds the display lights up regardless of gesture.In syslog.log it shows why              Aug 12 12:03:52 raspberrypi bedclock[1507]: Traceback (most recent call last):Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "/usr/lib/python3.7/multiprocAug 12 12:03:52 raspberrypi bedclock[1507]:     self.run()Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "./main.py", line 57, in runAug 12 12:03:52 raspberrypi bedclock[1507]:     motion.do_iterate()Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "/home/pi/bedclock.git/bedcloAug 12 12:03:52 raspberrypi bedclock[1507]:     do_iterate_proximity()Aug 12 12:03:52 raspberrypi bedclock[1507]:   File "/home/pi/bedclock.git/bedcloAug 12 12:03:52 raspberrypi bedclock[1507]:     newProximity = _state.apds.proxiAug 12 12:03:52 raspberrypi bedclock[1507]: TypeError: 'int' object is not callalines 1-21/21 (END)...skipping... does this log give you a hint at what could be wrongI have not found help anywhere else and am about to abandoned this project Thanks again for your help Jim On Wednesday, July 28, 2021, 08:53:45 PM EDT, Flavio Fernandes ***@***.***> wrote: Hmm.... sounds like you are having issues with the device indeed. Take a look at https://github.com/adafruit/Adafruit_CircuitPython_APDS9960 and see if you can get the basic examples working. Just to be clear, you are using the APDS9960 , not the 6660 right? I'm assuming you had a typo there. Another place to try is the discord for Adafruit folks. They know a lot about the i2c device. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for the log trace, @bobjimman . I now better understand the issue you are having.
It is not working because the Adafruit Library made a breaking change on Adafruit_CircuitPython_APDS9960 by 
@caternuson :
https://github.com/adafruit/Adafruit_CircuitPython_APDS9960/commit/637de6b55ccfcea853056659714bd036570b02c6

With that, proximity changes from a function to a property. At this point, I can either pin down the version of
the library that exposes proximity() as function, or change the bedclock code to use the new version of
the library. Let me think a little bit about the better approach and take the proper action.

Thanks,

-- flaviof

**Comment by flavio-fernandes** [comment]
@bobjimman Please pick the latest changes. With that, I hope you will no longer have the issue with the exception when getting the proximity value.
Alternatively, all you need is to remove the parenthesis in the following file/line:

https://github.com/flavio-fernandes/bedclock/blob/022747e59bc33f3d6806c5e18e4795f5678538fc/bedclock/motion.py#L176

Thank you for reporting this issue to me; I hope you get your bedclock working after this!

Best,

-- flaviof

**Comment by bobjimman** [comment]
Thanks for that info I've been trying everything it great that at least theres a path forward.I await you solution
ThanksJim



    On Saturday, August 14, 2021, 10:10:21 AM EDT, Flavio Fernandes ***@***.***> wrote:  
 
 



Hi Flavio I started the Bedclock new with a new pi SD card and a new APDS9960.The response is identical as before every 10 seconds the display lights up regardless of gesture.In syslog.log it shows why Aug 12 12:03:52 raspberrypi bedclock[1507]: Traceback (most recent call last):Aug 12 12:03:52 raspberrypi bedclock[1507]: File "/usr/lib/python3.7/multiprocAug 12 12:03:52 raspberrypi bedclock[1507]: self.run()Aug 12 12:03:52 raspberrypi bedclock[1507]: File "./main.py", line 57, in runAug 12 12:03:52 raspberrypi bedclock[1507]: motion.do_iterate()Aug 12 12:03:52 raspberrypi bedclock[1507]: File "/home/pi/bedclock.git/bedcloAug 12 12:03:52 raspberrypi bedclock[1507]: do_iterate_proximity()Aug 12 12:03:52 raspberrypi bedclock[1507]: File "/home/pi/bedclock.git/bedcloAug 12 12:03:52 raspberrypi bedclock[1507]: newProximity = _state.apds.proxiAug 12 12:03:52 raspberrypi bedclock[1507]: TypeError: 'int' object is not callalines 1-21/21 (END)...skipping... does this log give you a hint at what could be wrongI have not found help anywhere else and am about to abandoned this project Thanks again for your help Jim On Wednesday, July 28, 2021, 08:53:45 PM EDT, Flavio Fernandes @.***> wrote: Hmm.... sounds like you are having issues with the device indeed. Take a look at https://github.com/adafruit/Adafruit_CircuitPython_APDS9960 and see if you can get the basic examples working. Just to be clear, you are using the APDS9960 , not the 6660 right? I'm assuming you had a typo there. Another place to try is the discord for Adafruit folks. They know a lot about the i2c device. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


Thank you for the log trace, @bobjimman . I know better understand the issue you are having.
It is not working because the Adafruit Library made a breaking change on Adafruit_CircuitPython_APDS9960 by
@caternuson :
***@***.***

With that, proximity changes from a function to a property. At this point, I can either pin down the version of
the library that exposes proximity() as function, or change the bedclock code to use the new version of
the library. Let me think a little bit about the better approach and take the proper action.

Thanks,

-- flaviof

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by flavio-fernandes** [comment]
> Thanks for that info I've been trying everything it great that at least theres a path forward.I await you solution Thanks Jim 

No problem @bobjimman . Let me know if you encounter any other issues after picking up the fix I posted.
